apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: node-example-ns
spec:
  selector:
    app: node-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
